### ISSUE TITLE
Duplicate with multiple cursors on the same line should duplicate once

### ISSUE THREAD

**Issue by JoeyQuint** [kkapsner/vscode-duplicateselection#1]
**Steps to reproduce :**
1. Put 2 cursors on the same line, without selecting any text
2. Press `Ctrl+D` (or whatever your shortcut to duplicate is) to duplicate the current line.
You now have 3 lines: the original one, and 2 copies. The cursors are on the 2nd copy (the last line).
If you have 3 cursors, you will get 3 copies (ie. 4 lines). If you have 4 cursors, you will have 4 copies. Etc.

**Expected behavior:**
If all cursors are on the same line and no text is selected, that line should be copied only once, and not as many times as there are cursors on it.

Same applies if you have 2 cursors on one line, and 1 cursor on another line, the first line will be replicated as many times as it has cursors, instead of being copied only once.

**Comment by kkapsner** [comment]
Are you using these shortcuts?
```
{
	"key": "ctrl+d",
	"command": "editor.action.copyLinesDownAction",
	"when":  "editorTextFocus && !editorReadonly && !editorHasSelection"
},
{
	"key": "ctrl+d",
	"command": "duplicateselection.action.copySelectionForwardAction",
	"when": "editorTextFocus && !editorReadonly && editorHasSelection"
}
```

If so the upper part is responsible for the behaviour when nothing is selected which triggers a native vscode command (editor.action.copyLinesDownAction). This plugin only deals with selection and does not duplicate lines. Therefore there is little I can do about your problem.

Actually there is already an issue for this on vscode: https://github.com/Microsoft/vscode/issues/40646 and even a merge request with a fix (but as far as I see the cursors are not correct after the duplication): https://github.com/Microsoft/vscode/pull/52645

**Comment by JoeyQuint** [comment]
Oh indeed, I am using this shortcut and didn't realize it was the native VSCode feature. Thank you for the reply!
